# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2aa4018ef88b5d8dcadc986ee38af032af2164d2804447c5a74dfda3832051188ade1db373dd2a85447375dda1719cbc85fd882d3c421a916b18bd18fe703e87

test:
  secret_key_base: 9dc7b5e95c8e8df54bc303375a1dc676ef2aa817c8ec07c6f2756788f37e3e6c6ea2488661af0140625f9356212db8288ebb1dd4fcdc25bfca99f13495526b1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
